export const mockSensors = [
  {
    id: "1",
    name: "Downtown AQI Monitor",
    type: "AQI" as const,
    status: "streaming" as const,
    lastReading: 42,
    earnings: 127.5,
    location: "San Francisco, CA",
    owner: "7xKX...9mPq",
    uptime: 99.8,
    pricePerQuery: 0.01,
    monthlySubscription: 5.0,
  },
  {
    id: "2",
    name: "Harbor Temperature Sensor",
    type: "Temperature" as const,
    status: "streaming" as const,
    lastReading: 18.5,
    earnings: 89.2,
    location: "Seattle, WA",
    owner: "9pLm...3kRt",
    uptime: 98.5,
    pricePerQuery: 0.008,
    monthlySubscription: 4.0,
  },
  {
    id: "3",
    name: "Industrial Noise Monitor",
    type: "Noise" as const,
    status: "streaming" as const,
    lastReading: 65,
    earnings: 156.8,
    location: "Austin, TX",
    owner: "4mNb...7xQw",
    uptime: 97.2,
    pricePerQuery: 0.012,
    monthlySubscription: 6.0,
  },
  {
    id: "4",
    name: "Highway Traffic Counter",
    type: "Traffic" as const,
    status: "offline" as const,
    lastReading: 342,
    earnings: 203.4,
    location: "Los Angeles, CA",
    owner: "2kPl...8vMn",
    uptime: 95.1,
    pricePerQuery: 0.015,
    monthlySubscription: 7.5,
  },
  {
    id: "5",
    name: "Greenhouse Humidity Sensor",
    type: "Humidity" as const,
    status: "streaming" as const,
    lastReading: 72,
    earnings: 94.6,
    location: "Portland, OR",
    owner: "6tRx...4nLp",
    uptime: 99.2,
    pricePerQuery: 0.009,
    monthlySubscription: 4.5,
  },
  {
    id: "6",
    name: "Beach Weather Station",
    type: "Temperature" as const,
    status: "streaming" as const,
    lastReading: 22.3,
    earnings: 178.9,
    location: "Miami, FL",
    owner: "8xMn...2pKl",
    uptime: 98.9,
    pricePerQuery: 0.011,
    monthlySubscription: 5.5,
  },
]

export const mockRevenueData = [
  { date: "Jan", revenue: 45 },
  { date: "Feb", revenue: 52 },
  { date: "Mar", revenue: 61 },
  { date: "Apr", revenue: 58 },
  { date: "May", revenue: 73 },
  { date: "Jun", revenue: 89 },
  { date: "Jul", revenue: 127 },
]

export const mockSensorData = Array.from({ length: 24 }, (_, i) => ({
  time: `${i}:00`,
  value: Math.random() * 50 + 20,
}))
